DROP TABLE IF EXISTS Signage;

CREATE TABLE Signage (
 STREETNAME VARCHAR(100) NOT NULL,
 BUILDING MEDIUMINT NOT NULL,
 BUILDINGNAME VARCHAR(100) NOT NULL,
 NAME VARCHAR(100) NOT NULL,
 NUMBEROFSCREENS SMALLINT,
 HEIGHT VARCHAR(100),
 TYPE VARCHAR(100),
 ORIENTATION VARCHAR(100),
 AREA MEDIUMINT,
 PRIMARY KEY (STREETNAME, BUILDING, BUILDINGNAME, NAME)
);

DROP TABLE IF EXISTS InspectionResult;

CREATE TABLE InspectionResult (
 STREETNAME VARCHAR(100) NOT NULL,
 BUILDING MEDIUMINT NOT NULL,
 NAME VARCHAR(100) NOT NULL,
 INSPECTIONDATE DATE NOT NULL,
 VIOLATIONCODE VARCHAR(100) NOT NULL,
 DESCRIPTION VARCHAR(1000),
 CRITICALFLAG VARCHAR(100),
 SCORE TINYINT,
 GRADE VARCHAR(20),
 TYPE VARCHAR(100),
 PRIMARY KEY (STREETNAME, BUILDING, NAME, INSPECTIONDATE, VIOLATIONCODE)
);

DROP TABLE IF EXISTS TrafficAccident;

CREATE TABLE TrafficAccident (
 ONSTREET VARCHAR(100) NOT NULL,
 CROSSSTREET VARCHAR(100),
 PEDESTRIANINJURED SMALLINT,
 PEDESTRIANKILLED SMALLINT,
 CYCLISTINJURED SMALLINT,
 CYCLISTKILLED SMALLINT,
 MOTORISTINJURED SMALLINT,
 MOTORISTKILLED  SMALLINT
);

DROP TABLE IF EXISTS Hotel;

CREATE TABLE Hotel (
 STREETNAME VARCHAR(100) NOT NULL,
 BUILDING MEDIUMINT NOT NULL,
 NAME VARCHAR(100) NOT NULL,
 ZIPCODE VARCHAR(20),
 LONGITUDE DECIMAL(13,10),
 LATITUDE DECIMAL(13,10),
 PHONENUMBER VARCHAR(50),
 WEBSITE  VARCHAR(200),
 PRIMARY KEY (STREETNAME, BUILDING, NAME)
);

DROP TABLE IF EXISTS Entertainment;

CREATE TABLE Entertainment (
 STREETNAME VARCHAR(100) NOT NULL,
 BUILDING MEDIUMINT NOT NULL,
 NAME VARCHAR(100) NOT NULL,
 ZIPCODE VARCHAR(20),
 LONGITUDE DECIMAL(13,10),
 LATITUDE DECIMAL(13,10),
 PHONENUMBER VARCHAR(50),
 WEBSITE  VARCHAR(200),
 TYPE VARCHAR(50),
 PRIMARY KEY (STREETNAME, BUILDING, NAME)
);

DROP TABLE IF EXISTS Food;

CREATE TABLE Food (
 STREETNAME VARCHAR(100) NOT NULL,
 BUILDING MEDIUMINT NOT NULL,
 NAME VARCHAR(100) NOT NULL,
 ZIPCODE VARCHAR(20),
 LONGITUDE DECIMAL(13,10),
 LATITUDE DECIMAL(13,10),
 PHONENUMBER VARCHAR(50),
 WEBSITE  VARCHAR(200),
 CUISINE VARCHAR(50),
 PRIMARY KEY (STREETNAME, BUILDING, NAME)
);
