DROP TABLE Signage;

CREATE TABLE Signage (
    STREETNAME      VARCHAR2(100)   NOT NULL,
    BUILDING        NUMBER(10)      NOT NULL,
    BUILDINGNAME    VARCHAR2(100)   NOT NULL,
    NAME            VARCHAR2(100)   NOT NULL,
    NUMBEROFSCREENS NUMBER(5),
    HEIGHT          VARCHAR2(100),
    TYPE            VARCHAR2(100),
    ORIENTATION	    VARCHAR2(100),
    AREA		    NUMBER(10),
    CONSTRAINT PK_Signage PRIMARY KEY (STREETNAME, BUILDING, BUILDINGNAME, NAME)
);

COMMENT ON TABLE Signage IS 'Times Square Signage';

DROP TABLE InspectionResult;

CREATE TABLE InspectionResult (
    STREETNAME      VARCHAR2(100)   NOT NULL,
    BUILDING        NUMBER(10)      NOT NULL,
    NAME            VARCHAR2(100)   NOT NULL,
    INSPECTIONDATE  DATE            NOT NULL,
    VIOLATIONCODE   VARCHAR2(100)   NOT NULL,
    DESCRIPTION     VARCHAR2(1000),
    CRITICALFLAG    VARCHAR2(100),
    SCORE	        NUMBER(5),
    GRADE		    VARCHAR2(20),
    TYPE		    VARCHAR2(100),
    CONSTRAINT PK_InspectionResult PRIMARY KEY (STREETNAME, BUILDING, NAME, INSPECTIONDATE, VIOLATIONCODE)
);

COMMENT ON TABLE InspectionResult IS 'Times Square Restaurant Inspection Result';

DROP TABLE TrafficAccident;

CREATE TABLE TrafficAccident (
    ONSTREET            VARCHAR2(100)   NOT NULL,
    CROSSSTREET         VARCHAR2(100),
    PEDESTRIANINJURED   NUMBER(5),
    PEDESTRIANKILLED    NUMBER(5),
    CYCLISTINJURED      NUMBER(5),
    CYCLISTKILLED	    NUMBER(5),
    MOTORISTINJURED	    NUMBER(5),
    MOTORISTKILLED 	    NUMBER(5)
);

COMMENT ON TABLE TrafficAccident IS 'NYC Traffic Accident Logs';

DROP TABLE Hotel;

CREATE TABLE Hotel (
    STREETNAME      VARCHAR2(100)   NOT NULL,
    BUILDING        NUMBER(10)      NOT NULL,
    NAME            VARCHAR2(100)   NOT NULL,
    ZIPCODE         VARCHAR2(20),
    LONGITUDE       NUMBER(13,10),
    LATITUDE	    NUMBER(13,10),
    PHONENUMBER	    VARCHAR2(50),
    WEBSITE 	    VARCHAR2(200),
    CONSTRAINT PK_Hotel PRIMARY KEY (STREETNAME, BUILDING, NAME)
);

COMMENT ON TABLE Hotel IS 'Times Square Hotels';

DROP TABLE Entertainment;

CREATE TABLE Entertainment (
    STREETNAME      VARCHAR2(100)   NOT NULL,
    BUILDING        NUMBER(10)      NOT NULL,
    NAME            VARCHAR2(100)   NOT NULL,
    ZIPCODE         VARCHAR2(20),
    LONGITUDE       NUMBER(13,10),
    LATITUDE	    NUMBER(13,10),
    PHONENUMBER	    VARCHAR2(50),
    WEBSITE 	    VARCHAR2(200),
    TYPE            VARCHAR2(50),
    CONSTRAINT PK_Entertainment PRIMARY KEY (STREETNAME, BUILDING, NAME)
);

COMMENT ON TABLE Entertainment IS 'Times Square Entertainment Venues';

DROP TABLE Food;

CREATE TABLE Food (
    STREETNAME      VARCHAR2(100)   NOT NULL,
    BUILDING        NUMBER(10)      NOT NULL,
    NAME            VARCHAR2(100)   NOT NULL,
    ZIPCODE         VARCHAR2(20),
    LONGITUDE       NUMBER(13,10),
    LATITUDE	    NUMBER(13,10),
    PHONENUMBER	    VARCHAR2(50),
    WEBSITE 	    VARCHAR2(200),
    CUISINE         VARCHAR2(50),
    CONSTRAINT PK_Food PRIMARY KEY (STREETNAME, BUILDING, NAME)
);

COMMENT ON TABLE Food IS 'Times Square Food and Beverage Locations';


